[build]
  command = "yarn build"
  publish = "dist"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[functions]
  directory = "dist/functions"